version: "3"

tasks:
  generate:
    description: "Generate code from proto files"
    cmds:
      - export PATH="$PATH:$(go env GOPATH)/bin" && protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative